# Generated by Django 3.1.7 on 2021-03-28 00:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WikiScrapeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Category names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WikiScrapeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Food names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('img_src', models.CharField(max_length=1000, null=True)),
                ('categories', models.ManyToManyField(through='foods.CategoryAssignment', to='foods.WikiScrapeCategory')),
            ],
        ),
        migrations.AddField(
            model_name='wikiscrapecategory',
            name='foods',
            field=models.ManyToManyField(through='foods.CategoryAssignment', to='foods.WikiScrapeFood'),
        ),
        migrations.AddField(
            model_name='categoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.wikiscrapecategory'),
        ),
        migrations.AddField(
            model_name='categoryassignment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.wikiscrapefood'),
        ),
    ]
