# Generated by Django 3.1.5 on 2021-03-19 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiScrapeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Category names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.wikiscrapecategory')),
            ],
        ),
        migrations.CreateModel(
            name='WikiScrapeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Food names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('img_src', models.CharField(max_length=1000)),
                ('categories', models.ManyToManyField(to='foods.WikiScrapeCategory')),
            ],
        ),
    ]
