# Generated by Django 3.1.7 on 2021-04-01 04:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FdcCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Category names must be longer than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='FdcCategoryAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.fdccategory')),
            ],
        ),
        migrations.CreateModel(
            name='FdcFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdcId', models.CharField(max_length=20)),
                ('foodClass', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20000)),
                ('foodType', models.CharField(max_length=200)),
                ('foodCode', models.CharField(max_length=20)),
                ('totalRefuse', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=20000)),
                ('scientificName', models.CharField(max_length=500)),
                ('gtinUpc', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(through='review.FdcCategoryAssignment', to='review.FdcCategory')),
            ],
        ),
        migrations.CreateModel(
            name='WikiCategoryAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WikiScrapeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Category names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WikiScrapeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Food names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('img_src', models.CharField(max_length=1000, null=True)),
                ('categories', models.ManyToManyField(through='review.WikiCategoryAssignment', to='review.WikiScrapeCategory')),
            ],
        ),
        migrations.AddField(
            model_name='wikiscrapecategory',
            name='foods',
            field=models.ManyToManyField(through='review.WikiCategoryAssignment', to='review.WikiScrapeFood'),
        ),
        migrations.AddField(
            model_name='wikicategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikiscrapecategory'),
        ),
        migrations.AddField(
            model_name='wikicategoryassignment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikiscrapefood'),
        ),
        migrations.CreateModel(
            name='FdcWikiPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.fdcfood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wiki_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikiscrapefood')),
            ],
        ),
        migrations.CreateModel(
            name='FdcFoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('lastUpdated', models.CharField(max_length=50)),
                ('nutrient_id', models.IntegerField(null=True)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(null=True)),
                ('isNutrientLabel', models.BooleanField()),
                ('indentLevel', models.IntegerField(null=True)),
                ('shortestName', models.CharField(max_length=200)),
                ('nutrientUnit', models.CharField(max_length=50)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.fdcfood')),
            ],
        ),
        migrations.CreateModel(
            name='FdcFoodMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.CharField(max_length=100)),
                ('gramWeight', models.CharField(max_length=20)),
                ('disseminationText', models.CharField(max_length=2000)),
                ('rank', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=40)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.fdcfood')),
            ],
        ),
        migrations.AddField(
            model_name='fdcfood',
            name='foods',
            field=models.ManyToManyField(through='review.FdcWikiPairing', to='review.WikiScrapeFood'),
        ),
        migrations.AddField(
            model_name='fdccategoryassignment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.fdcfood'),
        ),
    ]
