# Generated by Django 3.1.7 on 2021-04-08 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('column', models.PositiveSmallIntegerField(null=True)),
                ('isCategory', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=20)),
                ('scraped', models.BooleanField(default=False)),
                ('food_count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsdaFood',
            fields=[
                ('fdc_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=20000)),
                ('dataType', models.CharField(max_length=200)),
                ('foodClass', models.CharField(max_length=200)),
                ('foodCode', models.CharField(max_length=20, null=True)),
                ('totalRefuse', models.CharField(max_length=20, null=True)),
                ('ingredients', models.CharField(max_length=20000, null=True)),
                ('scientificName', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(max_length=500, null=True)),
                ('gtinUpc', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Category names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiCategoryAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikicategory')),
            ],
        ),
        migrations.CreateModel(
            name='WikiFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Food names must be longer than 1 character')])),
                ('description', models.CharField(max_length=30000)),
                ('wiki_url', models.CharField(max_length=1000, unique=True)),
                ('img_src', models.CharField(max_length=1000, null=True)),
                ('paired', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, through='review.WikiCategoryAssignment', to='review.WikiCategory')),
            ],
        ),
        migrations.AddField(
            model_name='wikicategoryassignment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikifood'),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='foods',
            field=models.ManyToManyField(blank=True, through='review.WikiCategoryAssignment', to='review.WikiFood'),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.wikicategory'),
        ),
        migrations.CreateModel(
            name='UsdaNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('unitName', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('number', 'unitName')},
            },
        ),
        migrations.CreateModel(
            name='UsdaFoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdanutrient')),
                ('usda_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wikicategoryassignment',
            unique_together={('food', 'category')},
        ),
        migrations.CreateModel(
            name='UsdaWikiPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usda_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood')),
                ('wiki_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikifood')),
            ],
            options={
                'unique_together': {('usda_food', 'wiki_food')},
            },
        ),
        migrations.CreateModel(
            name='UsdaFoodPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portionDescription', models.CharField(max_length=200, null=True)),
                ('modifier', models.CharField(max_length=100)),
                ('gramWeight', models.CharField(max_length=20)),
                ('sequenceNumber', models.PositiveIntegerField(null=True)),
                ('usda_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood')),
            ],
            options={
                'unique_together': {('portionDescription', 'usda_food')},
            },
        ),
    ]
