# Generated by Django 3.1.7 on 2021-04-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikifood',
            name='paired',
        ),
    ]
