# Generated by Django 3.1.7 on 2021-04-04 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdaFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdcId', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20000)),
                ('foodClass', models.CharField(max_length=200)),
                ('foodCode', models.CharField(max_length=20, null=True)),
                ('totalRefuse', models.CharField(max_length=20, null=True)),
                ('ingredients', models.CharField(max_length=20000, null=True)),
                ('scientificName', models.CharField(max_length=500, null=True)),
                ('gtinUpc', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsdaFoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsdaFoodPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portionDescription', models.CharField(max_length=200)),
                ('modifier', models.CharField(max_length=100)),
                ('gramWeight', models.CharField(max_length=20)),
                ('sequenceNumber', models.IntegerField(null=True)),
                ('usda_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood')),
            ],
        ),
        migrations.CreateModel(
            name='UsdaNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(null=True)),
                ('unitName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsdaWikiPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usda_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood')),
                ('wiki_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.wikiscrapefood')),
            ],
        ),
        migrations.RemoveField(
            model_name='fdccategoryassignment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fdccategoryassignment',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fdcfood',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='fdcfood',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='fdcfoodmeasure',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fdcfoodnutrient',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fdcwikipairing',
            name='fdc_food',
        ),
        migrations.RemoveField(
            model_name='fdcwikipairing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fdcwikipairing',
            name='wiki_food',
        ),
        migrations.DeleteModel(
            name='FdcCategory',
        ),
        migrations.DeleteModel(
            name='FdcCategoryAssignment',
        ),
        migrations.DeleteModel(
            name='FdcFood',
        ),
        migrations.DeleteModel(
            name='FdcFoodMeasure',
        ),
        migrations.DeleteModel(
            name='FdcFoodNutrient',
        ),
        migrations.DeleteModel(
            name='FdcWikiPairing',
        ),
        migrations.AddField(
            model_name='usdafoodnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdanutrient'),
        ),
        migrations.AddField(
            model_name='usdafoodnutrient',
            name='usda_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.usdafood'),
        ),
    ]
