# Generated by Django 3.1.7 on 2021-04-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210404_0434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usdanutrient',
            unique_together={('number', 'unitName')},
        ),
    ]
