# Generated by Django 3.1.7 on 2021-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_wikifood_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikifood',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
