# Generated by Django 3.1.7 on 2021-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_wikifood_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdawikipairing',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
