# Generated by Django 3.1.7 on 2021-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210404_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiscrapefood',
            name='paired',
            field=models.BooleanField(null=True),
        ),
    ]
