# Generated by Django 3.1.7 on 2021-04-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_wikiscrapefood_paired'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usdawikipairing',
            unique_together={('usda_food', 'wiki_food')},
        ),
    ]
