# Generated by Django 3.1.7 on 2021-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210404_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdafoodportion',
            name='portionDescription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
