# Generated by Django 3.1.7 on 2021-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20210404_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiscrapefood',
            name='wiki_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
