# Generated by Django 3.1.7 on 2021-04-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20210404_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiscrapecategory',
            name='wiki_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usdafoodportion',
            unique_together={('portionDescription', 'usda_food')},
        ),
        migrations.AlterUniqueTogether(
            name='wikicategoryassignment',
            unique_together={('food', 'category')},
        ),
    ]
