# Generated by Django 3.1.7 on 2021-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20210404_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiscrapefood',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
