# Generated by Django 3.1.7 on 2021-04-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20210404_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wiki_url', models.CharField(max_length=1000)),
                ('column', models.IntegerField(null=True)),
                ('isCategory', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
