# Generated by Django 3.1.7 on 2021-04-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_scrapable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapable',
            name='wiki_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
