# Generated by Django 3.1.7 on 2021-04-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20210406_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapable',
            old_name='wiki_url',
            new_name='url',
        ),
    ]
